# Generated by Django 6.0.1 on 2026-04-07 00:00

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('students_count', models.PositiveIntegerField()),
                ('grade', models.PositiveSmallIntegerField(default=1)),
                ('parallel', models.CharField(default='A', max_length=2)),
                ('education_level', models.CharField(choices=[('primary', 'начальное'), ('basic', 'основное'), ('high', 'среднее')], max_length=20)),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('ordinary', 'обычный'), ('lab', 'лабораторный'), ('computer', 'компьютерный')], max_length=50)),
            ],
            options={
                'verbose_name': 'кабинет',
                'verbose_name_plural': 'кабинеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('operation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'лог интеграции',
                'verbose_name_plural': 'логи интеграции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField(verbose_name='номер урока')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_type', models.CharField(choices=[('normal', 'обычный'), ('short', 'сокращённый')], max_length=20)),
            ],
            options={
                'verbose_name': 'время урока',
                'verbose_name_plural': 'времена уроков',
                'ordering': ['day_type', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=2)),
                ('required_room_type', models.CharField(choices=[('ordinary', 'обычный'), ('lab', 'лабораторный'), ('computer', 'компьютерный')], default='ordinary', max_length=50)),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель'), ('dispatcher', 'Диспетчер'), ('admin', 'Администратор')], default='student', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scheduler.class', verbose_name='класс')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['full_name', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('workload_hours', models.PositiveIntegerField(verbose_name='максимальная нагрузка в неделю')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='scheduler.user')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ['user__full_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.PositiveIntegerField(verbose_name='часов в неделю')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='scheduler.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='scheduler.subject')),
            ],
            options={
                'verbose_name': 'класс-предмет',
                'verbose_name_plural': 'классы-предметы',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', through='scheduler.ClassSubject', to='scheduler.subject'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')])) ,
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='scheduler.lessontime')),
            ],
            options={
                'verbose_name': 'временной слот',
                'verbose_name_plural': 'временные слоты',
                'ordering': ['weekday', 'lesson_time__day_type', 'lesson_time__lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveIntegerField(blank=True, null=True, verbose_name='часов в неделю для этого преподавателя')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='scheduler.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='scheduler.teacher')),
            ],
            options={
                'verbose_name': 'назначение преподавателя',
                'verbose_name_plural': 'назначения преподавателей',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='scheduler.timeslot')),
            ],
            options={
                'verbose_name': 'доступность преподавателя',
                'verbose_name_plural': 'доступность преподавателей',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.class')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.timeslot')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['lesson_date', 'time_slot__weekday', 'time_slot__lesson_time__lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('teacher_substitution', 'замена преподавателя'), ('reschedule', 'перенос'), ('cancel', 'отмена')], max_length=50)),
                ('description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'изменение расписания',
                'verbose_name_plural': 'изменения расписания',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('grade', 'parallel'), name='unique_grade_parallel'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_obj', 'subject'), name='unique_class_subject'),
        ),
        migrations.AddConstraint(
            model_name='lessontime',
            constraint=models.UniqueConstraint(fields=('lesson_number', 'day_type'), name='unique_lesson_number_day_type'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('weekday', 'lesson_time'), name='unique_weekday_lesson_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'class_obj'), name='unique_teaching_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('teacher', 'time_slot'), name='unique_teacher_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('class_obj', 'lesson_date', 'time_slot'), name='unique_class_date_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('teacher', 'lesson_date', 'time_slot'), name='unique_teacher_date_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('classroom', 'lesson_date', 'time_slot'), name='unique_classroom_date_time_slot'),
        ),
    ]
