# Generated by Django 6.0.1 on 2026-04-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyClassSubjectLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='начало недели')),
                ('weekly_hours', models.PositiveSmallIntegerField(verbose_name='часов в неделю')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_loads', to='scheduler.classsubject', verbose_name='класс-предмет')),
            ],
            options={
                'verbose_name': 'недельная нагрузка класса по предмету',
                'verbose_name_plural': 'недельные нагрузки классов по предметам',
                'ordering': ['-week_start', 'class_subject__class_obj__name', 'class_subject__subject__name'],
                'constraints': [models.UniqueConstraint(fields=('week_start', 'class_subject'), name='unique_week_start_class_subject_load')],
            },
        ),
    ]
