# Generated by Django 6.0.1 on 2026-04-19 00:00

from django.db import migrations, models


def seed_teacher_availability_status(apps, schema_editor):
    TeacherAvailability = apps.get_model('scheduler', 'TeacherAvailability')
    TeacherAvailability.objects.filter(is_available=True).update(status='working')
    TeacherAvailability.objects.filter(is_available=False).update(status='day_off')


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_weeklyclasssubjectload'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='status',
            field=models.CharField(
                choices=[
                    ('working', 'Работает'),
                    ('day_off', 'Не работает'),
                    ('sick', 'Болеет'),
                ],
                default='working',
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_teacher_availability_status, migrations.RunPython.noop),
    ]
