# Generated by Django 6.0.1 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_teacheravailability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='teacheravailability',
            name='unique_teacher_time_slot',
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(
                condition=models.Q(week_start__isnull=True),
                fields=('teacher', 'time_slot'),
                name='unique_teacher_time_slot_default',
            ),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(
                condition=models.Q(week_start__isnull=False),
                fields=('teacher', 'time_slot', 'week_start'),
                name='unique_teacher_time_slot_week',
            ),
        ),
    ]
